---
title: "Code5_GSEA"
output: html_document
date: "2025-07-14"
---

```{r}

library(readr)
library(patchwork)
library(clusterProfiler)
library(org.Mm.eg.db)
library(org.Hs.eg.db)
library(msigdbr)
library(enrichplot)
library(cowplot)
library(readxl)
library(tidyverse)

```

#comparison with molecular function pathways, mouse
```{r}

Data <- read_xlsx("MIF_markersMF.xlsx")
Data <- Data %>%
  dplyr::select(avg_log2FC, gene)
  
genelist <- Data$avg_log2FC
names(genelist) <- Data$gene

genelist <- sort(genelist, decreasing = TRUE)

names(genelist)[duplicated(names(genelist))]

head(genelist, 5)
any(genelist == 0)
any(is.na(genelist))
any(names(genelist) == 0)
any(is.na(names(genelist)))

table(is.finite(genelist)) 

GOMF_set <- msigdbr(species = "Mus musculus", category = "C5", subcategory = "MF")

GOMFTerm2 <- GOMF_set %>% dplyr::select(gs_name, gene_symbol)

GOMF <- GSEA(geneList = genelist,
                              TERM2GENE = GOMFTerm2,
                              minGSSize = 15,
                              pvalueCutoff = 0.05,
                              verbose = TRUE)

ridgeplot(GOMF)

```


```{r}

p1 <- gseaplot2(GOMF, geneSetID = "GOMF_VOLTAGE_GATED_MONOATOMIC_CATION_CHANNEL_ACTIVITY", title = "GOMF_VOLTAGE_GATED_MONOATOMIC_CATION_CHANNEL_ACTIVITY")
p2 <- gseaplot2(GOMF, geneSetID = "GOMF_POTASSIUM_CHANNEL_ACTIVITY", title = "GOMF_POTASSIUM_CHANNEL_ACTIVITY")
p3 <- gseaplot2(GOMF, geneSetID = "GOMF_VOLTAGE_GATED_CHANNEL_ACTIVITY", title = "GOMF_VOLTAGE_GATED_CHANNEL_ACTIVITY")
p4 <- gseaplot2(GOMF, geneSetID = "GOMF_MONOATOMIC_CATION_CHANNEL_ACTIVITY", title = "GOMF_MONOATOMIC_CATION_CHANNEL_ACTIVITY")
p5 <- gseaplot2(GOMF, geneSetID = "GOMF_G_PROTEIN_COUPLED_RECEPTOR_ACTIVITY", title = "GOMF_G_PROTEIN_COUPLED_RECEPTOR_ACTIVITY")
p6 <- gseaplot2(GOMF, geneSetID = "GOMF_METAL_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY", title = "GOMF_METAL_ION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY")

gg_p1 <- grid::grid.grabExpr({print(p1)})
gg_p2 <- grid::grid.grabExpr({print(p2)})
gg_p3 <- grid::grid.grabExpr({print(p3)})
gg_p4 <- grid::grid.grabExpr({print(p4)})
gg_p5 <- grid::grid.grabExpr({print(p5)})
gg_p6 <- grid::grid.grabExpr({print(p6)})

wrap_plots(list(gg_p1, gg_p2, gg_p3, gg_p4, gg_p5, gg_p6))

```

#comparison with molecular function pathways, human
```{r}

Data <- read_xlsx("ranked_lists/MIF_markersHsMF.xlsx")
Data <- Data %>%
  dplyr::select(avg_log2FC, gene)
  
genelist <- Data$avg_log2FC
names(genelist) <- Data$gene

genelist <- sort(genelist, decreasing = TRUE)

names(genelist)[duplicated(names(genelist))]

head(genelist, 5)
any(genelist == 0)
any(is.na(genelist))
any(names(genelist) == 0)
any(is.na(names(genelist)))

table(is.finite(genelist))

GOMF_set <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "MF")
GOMFTerm2 <- GOMF_set %>% dplyr::select(gs_name, gene_symbol)

GOMF <- GSEA(geneList = genelist,
                              TERM2GENE = GOMFTerm2,
                              minGSSize = 15,
                              pvalueCutoff = 0.05,
                              verbose = TRUE)

ridgeplot(GOMF)

```

```{r}

p1 <- gseaplot2(GOMF, geneSetID = "GOMF_CALCIUM_ION_BINDING", title = "CALCIUM ION BINDING")
p2 <- gseaplot2(GOMF, geneSetID = "GOMF_PASSIVE_TRANSMEMBRANE_TRANSPORTER_ACTIVITY", title = "PASSIVE TRANSMEMBRANE TRANSPORTER ACTIVITY")
p3 <- gseaplot2(GOMF, geneSetID = "GOMF_MONOATOMIC_ANION_TRANSMEMBRANE_TRANSPORTER_ACTIVITY", title = "MONOATOMIC ANION TRANSMEMBRANE TRANSPORTER ACTIVITY")
p4 <- gseaplot2(GOMF, geneSetID = "GOMF_CALCIUM_DEPENDENT_PROTEIN_BINDING", title = "CALCIUM DEPENDENT PROTEIN BINDING")
p5 <- gseaplot2(GOMF, geneSetID = "GOMF_MONOATOMIC_ANION_CHANNEL_ACTIVITY", title = "MONOATOMIC ANION CHANNEL ACTIVITY")
p6 <- gseaplot2(GOMF, geneSetID = "GOMF_CHLORIDE_TRANSMEMBRANE_TRANSPORTER_ACTIVITY", title = "CHLORIDE TRANSMEMBRANE TRANSPORTER ACTIVITY")
p7 <- gseaplot2(GOMF, geneSetID = "GOMF_CHLORIDE_CHANNEL_ACTIVITY", title = "CHLORIDE CHANNEL ACTIVITY")

gg_p1 <- grid::grid.grabExpr({print(p1)})
gg_p2 <- grid::grid.grabExpr({print(p2)})
gg_p3 <- grid::grid.grabExpr({print(p3)})
gg_p4 <- grid::grid.grabExpr({print(p4)})
gg_p5 <- grid::grid.grabExpr({print(p5)})
gg_p6 <- grid::grid.grabExpr({print(p6)})
gg_p7 <- grid::grid.grabExpr({print(p7)})

wrap_plots(list(gg_p1, gg_p2, gg_p3, gg_p4, gg_p5, gg_p6, gg_p7))

```


```{r}

ICCTerm2 <- read_xlsx("ICC.xlsx", sheet = 1)
SMCTerm2 <- read_xlsx("SMC.xlsx", sheet = 1)
MIFTerm2 <- read_xlsx("MIF.xlsx", sheet = 1)
FIBTerm2 <- read_xlsx("FIB.xlsx", sheet = 1)
ENSTerm2 <- read_xlsx("ENS.xlsx", sheet = 1)

ICC <- GSEA(geneList = genelist,
                              TERM2GENE = ICCTerm2,
                              minGSSize = 15,
                              pvalueCutoff = 0.05,
                              verbose = TRUE,
                              scoreType="pos")

SMC <- GSEA(geneList = genelist,
                              TERM2GENE = SMCTerm2,
                              minGSSize = 15,
                              pvalueCutoff = 0.05,
                              verbose = TRUE)

MIF <- GSEA(geneList = genelist,
                              TERM2GENE = MIFTerm2,
                              minGSSize = 15,
                              pvalueCutoff = 0.05,
                              verbose = TRUE,
                              scoreType="pos")

ENS <- GSEA(geneList = genelist,
                              TERM2GENE = ENSTerm2,
                              minGSSize = 15,
                              pvalueCutoff = 0.05,
                              verbose = TRUE)

FIB <- GSEA(geneList = genelist,
                              TERM2GENE = FIBTerm2,
                              minGSSize = 15,
                              pvalueCutoff = 0.05,
                              verbose = TRUE,
                              scoreType="pos")

```

```{r}

gseaplot2(ICC, geneSetID = "ICC", title = "ICC")

```

```{r}

gseaplot2(SMC, geneSetID = "SMC", title = "SMC")

```

```{r}

gseaplot2(MIF, geneSetID = "MIF", title = "MIF")

```

```{r}

gseaplot2(ENS, geneSetID = "ENS", title = "ENS")

```

```{r}

gseaplot2(FIB, geneSetID = "FIB", title = "FIB")

```

```{r}

NES <- c(MIF@result[["NES"]], FIB@result[["NES"]], ICC@result[["NES"]], SMC@result[["NES"]], ENS@result[["NES"]])
CellType <- c("MIF", "FIB", "ICC", "SMC", "ENS")

Data <- data.frame(NES, CellType)

Data %>%
  mutate(CellType = fct_relevel(CellType, "MIF", "ICC", "FIB", "SMC", "ENS"))%>%
  ggplot(., aes(CellType, NES, fill = CellType))+
  geom_bar(stat = "identity")+
  theme_minimal()+
  scale_fill_manual(values = c("#09A07A", "#0960A0", "#10D8FF", "#697BFB", "#C954F0"))

```
