---
title: "Code3_human_normal_integration_scRNAseq"
output: html_document
date: "2025-07-14"
---

```{r}

library(Seurat)
library(tidyverse)
library(patchwork)
library(cowplot)
library(hdf5r)
library(gdata)
library(WriteXLS)
library(RColorBrewer)


```


```{r}

PatientData <- readxl::read_xlsx("/dir/Patient_data.xlsx")


EpiMetadata <- readxl::read_xlsx("/dir/EpiMetadata.xlsx")
EpiMetadata <- as.data.frame(EpiMetadata)

EpiMetadata <- EpiMetadata %>% 
  left_join(., PatientData, by=c("patient.ID"))


NonEpiMetadata <- readxl::read_xlsx("/dir/NonEpiMetadata.xlsx")
NonEpiMetadata <- as.data.frame(NonEpiMetadata)

NonEpiMetadata <- NonEpiMetadata %>% 
  left_join(., PatientData, by=c("patient.ID"))


rownames(EpiMetadata) <- (EpiMetadata$cell.ID)
rownames(NonEpiMetadata) <- (NonEpiMetadata$cell.ID)


Epi <- Read10X_h5("/dir/Epithelial_Count_matrix.h5", use.names = TRUE, unique.features = TRUE)
NonEpi <- Read10X_h5("/dir/NonEpithelial_Count_matrix.h5", use.names = TRUE, unique.features = TRUE)

SeuObjEpi <- CreateSeuratObject(counts = Epi, project = "Epithelial",  min.cells = 3, min.features = 200, meta.data = EpiMetadata)
SeuObjNonEpi <- CreateSeuratObject(counts = NonEpi, project = "NonEpithelial",  min.cells = 3, min.features = 200, meta.data = NonEpiMetadata)

SeuObjEpi <- subset(SeuObjEpi, subset = sample.origin == "Normal" )
SeuObjNonEpi <- subset(SeuObjNonEpi, subset = sample.origin == "Normal" )

```

```{r}
 
VlnPlot(SeuObjEpi, features = c( "nFeature_RNA", "nCount_RNA", "percent.mt"),  ncol=3, split.by = "orig.ident", pt.size = 0.1)

```

```{r}

SeuObjEpiSub <- subset(SeuObjEpi, subset = nCount_RNA < 25000 & nFeature_RNA < 6000)

VlnPlot(SeuObjEpiSub, features = c( "nFeature_RNA", "nCount_RNA", "percent.mt"),  ncol=3, split.by = "orig.ident", pt.size = 0.1)

```

```{r}

VlnPlot(SeuObjNonEpi, features = c( "nFeature_RNA", "nCount_RNA", "percent.mt"),  ncol=3, split.by = "orig.ident", pt.size = 0.1)

```

```{r}

SeuObjNonEpiSub <- subset(SeuObjNonEpi, subset = nCount_RNA < 35000 & nFeature_RNA <4500)

VlnPlot(SeuObjNonEpiSub, features = c( "nFeature_RNA", "nCount_RNA", "percent.mt"),  ncol=3, split.by = "orig.ident", pt.size = 0.1)

```

```{r}

CRC16 <- subset(SeuObjNonEpiSub, subset = orig.ident == "CRC16")
CRC16@meta.data[["orig.ident2"]] <- "stroma"

KUL3 <- subset(SeuObjNonEpiSub, subset = orig.ident == "KUL3")
KUL3@meta.data[["orig.ident2"]] <- "stroma"

KUL5 <- subset(SeuObjNonEpiSub, subset = orig.ident == "KUL5")
KUL5@meta.data[["orig.ident2"]] <- "stroma"

SMC <- subset(SeuObjNonEpiSub, subset = orig.ident == "SMC")
SMC@meta.data[["orig.ident2"]] <- "stroma"


Epi_CRC16 <- subset(SeuObjEpiSub, subset = orig.ident == "CRC16")
Epi_CRC16@meta.data[["orig.ident2"]] <- "epi"

Epi_KUL3 <- subset(SeuObjEpiSub, subset = orig.ident == "KUL3")
Epi_KUL3@meta.data[["orig.ident2"]] <- "epi"

Epi_KUL5 <- subset(SeuObjEpiSub, subset = orig.ident == "KUL5")
Epi_KUL5@meta.data[["orig.ident2"]] <- "epi"

Epi_SMC <- subset(SeuObjEpiSub, subset = orig.ident == "SMC")
Epi_SMC@meta.data[["orig.ident2"]] <- "epi"


CRC16 <- merge(CRC16, y = Epi_CRC16)
KUL3 <- merge(KUL3, y = Epi_KUL3)
KUL5 <- merge(KUL5, y = Epi_KUL5)
SMC <- merge(SMC, y = Epi_SMC)


datalist <- list(CRC16, KUL3, KUL5, SMC)


for (i in 1:length(datalist)) {
    datalist[[i]] <- SCTransform(datalist[[i]], vars.to.regress = c("percent.mt"))
    }

features <- SelectIntegrationFeatures(object.list = datalist, nfeatures = 3000)
datalist <- PrepSCTIntegration(object.list = datalist, anchor.features = features)
datalist <- lapply(X = datalist, FUN = RunPCA, features = features)
anchors <- FindIntegrationAnchors(object.list = datalist, normalization.method = "SCT",  anchor.features = features, reduction = "rpca", k.anchor = 10)

DataIntegratedHs <- IntegrateData(anchorset = anchors, normalization.method = "SCT")

DefaultAssay(DataIntegratedHs) <- "integrated"

DataIntegratedHs <- RunPCA(DataIntegratedHs, verbose = FALSE)
ElbowPlot(DataIntegratedHs)
DataIntegratedHs <- RunUMAP(DataIntegratedHs, reduction = "pca", dims = 1:25)

DataIntegratedHs <- FindNeighbors(DataIntegratedHs, reduction = "pca", dims = 1:25)
DataIntegratedHs <- FindClusters(DataIntegratedHs, resolution = 0.5)


DefaultAssay(DataIntegratedHs) <- "RNA"

DataIntegratedHs <- NormalizeData(DataIntegratedHs, verbose = F)
DataIntegratedHs <- FindVariableFeatures(DataIntegratedHs, selection.method = "vst", nfeatures = 3000, verbose = FALSE)
DataIntegratedHs <- ScaleData(DataIntegratedHs, verbose = FALSE)

DimPlot(DataIntegratedHs, reduction = "umap", raster =F, label =T)

```

```{r}

DefaultAssay(DataIntegratedHs) <- "RNA"

FeaturePlot(DataIntegratedHs, c("PDGFRA", "ACTA2", "RGS5", "VTN", "CSPG4", "PECAM1", "LYVE1", "EPCAM", "S100B", "PTPRC", "FAP"), order = T)

```

```{r}

DimPlot(DataIntegratedHs, label = F, split.by = "orig.ident2")

```

```{r}

DimPlot(DataIntegratedHs, label = T, split.by = "Patient.ID")

```

```{r}

DataIntegratedHs <- subset(DataIntegrated, invert = T, patient.ID == "CRC2786")

DataIntegrated2Hs <- subset(DataIntegratedHs, idents = c(5,8,16,26, 12, 10, 13,14,17,24))

DefaultAssay(DataIntegrated2Hs) <- "integrated"

DataIntegrated2Hs <- RunPCA(DataIntegrated2Hs, verbose = FALSE)
ElbowPlot(DataIntegrated2Hs)
DataIntegrated2Hs <- RunUMAP(DataIntegrated2Hs, reduction = "pca", dims = 1:20)

DataIntegrated2Hs <- FindNeighbors(DataIntegrated2Hs, reduction = "pca", dims = 1:20)
DataIntegrated2Hs <- FindClusters(DataIntegrated2Hs, resolution = 0.4)

DimPlot(DataIntegrated2Hs, label = T)

```

```{r}

DimPlot(DataIntegrated2Hs, label = F, split.by = "orig.ident2")

```


```{r}

Markers <- FindAllMarkers(DataIntegrated2Hs, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, min.diff.pct = 0.25, assay = "RNA")

top10 <- Markers %>%
  top_n(n = 10, wt = avg_log2FC)

DefaultAssay(DataIntegrated2Hs) <- "RNA"

VlnPlot(DataIntegrated2Hs, features = rownames(top10), pt.size = 0)

```

```{r}

ClusterIDs <- c("MAF", "SAF","epith_stem_prog", "MIF", "glia", "VEC",
                "SEMF", "peri", "MM_SMC/MP_SMC", "peri", "Goblet",
                "LP_SMC", "LEC", "colonocyte", "endoth+peri")

names(ClusterIDs) <- levels(DataIntegrated2Hs)
DataIntegrated2Hs <- RenameIdents(DataIntegrated2Hs, ClusterIDs)

DimPlot(DataIntegrated2Hs,
               cols = c("SEMF" = "#F6A937", "MAF" = "#1D7BFC", 'SAF' = '#129B93',  "MIF" = "#035C56", 
             "LP_SMC" = "#C51B7C", "MM_SMC/MP_SMC" = "#C59ED4",
             "peri" = "#6E5F57", "endoth+peri" = "#A89E99", "VEC" = "#E1E0DF", "LEC" = "#47362E",
              "glia" = "#C2D9F0",
            "epith_stem_prog" = "#EACAB4",  "colonocyte" = "#C3936D", "Goblet" = "#734724")) & NoAxes()

saveRDS(DataIntegrated2Hs, file="/dir/Hs_colon_integration.rds")

```

```{r}

DimPlot(DataIntegrated2Hs, split.by = "patient.ID", ncol = 10, group.by = "orig.ident",
        cols = c("SEMF" = "#F6A937", "MAF" = "#1D7BFC", 'SAF' = '#129B93',  "MIF" = "#035C56", 
             "LP_SMC" = "#C51B7C", "MM_SMC/MP_SMC" = "#C59ED4",
             "peri" = "#6E5F57", "endoth+peri" = "#A89E99", "VEC" = "#E1E0DF", "LEC" = "#47362E",
              "glia" = "#C2D9F0",
            "epith_stem_prog" = "#EACAB4",  "colonocyte" = "#C3936D", "Goblet" = "#734724"))

```

```{r}

DataIntegrated2Hs@active.ident <- factor(DataIntegrated2Hs@active.ident,
                                       levels = c("Goblet", "colonocyte","epith_stem_prog", "glia",
                                                  "LEC",  "VEC", "endoth+peri", "peri",
                                                   "MM_SMC/MP_SMC","LP_SMC", 
                                                  "MIF", "SAF",  "MAF", "SEMF"))

genes <- c("PDGFRA", "FOXL1","F3", "PROCR", "BMP5", "BMP7", "WNT5A", "ACTA2",  "WNT4",
           "CD34" , "CD81",  "WNT2B", "GREM1", "GREM2", "RSPO3", "WNT2", "LAMA5", "WIF1","PI16", "KCNN3")

DotPlot(DataIntegrated2Hs, assay = "RNA", dot.min = 0.05,  genes, scale.by = "size")+
    theme(axis.text=element_text(angle=90))

```

```{r}

genes <- c( "BMP7",  "FGF9", "COL4A5", "COL4A6","AGT", "NRG1", "GLP2R",   "TRPA1",
            "SOX6","CXCL14", "EDNRB", "BMP5","INSC",   "LAMA5",
            "VSTM2A", "NSG1", "ENHO", 
            "HSD17B2", "FRZB", "PROM1", "F2R", "PDGFD", "DMKN", 
            
            "VCAM1", "CCL8", "HAPLN1",
            "EDIL3",   "STMN2",
            "ADAM28", "ADAMDEC1", "ABCA8",
            "SFTA1P",
            
            "MEDAG", "PI16","PCOLCE2", "CILP", "OSR2",
             "C3", "HAS1", "ADAMTS5", "AR", "ACKR4",
            "F10", "WISP2",
            "FBLN2", "SFRP1", "SFRP2", "IGF1", "SLPI",
            
           
          "KCNN3",  "P2RY1", "RAMP1", "FIBIN", "SMOC2",
          "PID1", "THBS2", "JAM2", "FXYD6", "MGP",
          "THBS4", "FNDC1", "ADAMTSL3",
          "C7")

DotPlot(DataIntegrated2Hs, assay = "RNA", dot.min = 0.05,  genes, scale.by = "size")+
    theme(axis.text=element_text(angle=90))

```

```{r}

genes <- c("ACTA2",  "LMOD1",  "CNN1", "TAGLN", "MYH11", "MYL9",  "MYLK",  "ACTG2","DES",
            "PDGFRB", "CSPG4" , "NOTCH3",
            "FLT1","PECAM1", 
            "LYVE1",  "FLT4", "PROX1",
            "S100B", "UCHL1",
            "EPCAM", "LGR5", "OLFM4", "CEACAM7", "BEST4", "FABP2", "MUC2")

DotPlot(DataIntegrated2Hs, assay = "RNA", dot.min = 0.05,  genes, scale.by = "size")+
    theme(axis.text=element_text(angle=0))

```

```{r}

FeaturePlot(DataIntegrated2Hs, c("CCL19", "ANO1", "KIT"), order =T) & NoAxes()

```

```{r}

genes <- c(
  "FGF7", "CD38", "CCDC3", 
  "ALDH1A1",   "OGN","THBD", "GNAI1", "BMP3", "WIF1",
  "CXCL10" ,"TNFAIP2" ,  "HCAR2", "PRRX2",
   "IGFBP3", "CXCL16", "SERPINA3N","IGFPB5",  "FGF10",  "RAD51B", "SCUBE1","LEPR",
  "OSR1",  "TNFSF13B", "ELN","CD248", 
   "SCARA5", "IL33", "DPEP1",  "GFPT2")


DotPlot(DataIntegrated2, assay = "RNA", dot.min = 0.05,  genes, scale.by = "size", col.min = 0)+
    theme(axis.text=element_text(angle=90))

```

```{r}

genelist5 <- list(c("GREM1", "GREM2", "RSPO3"))
DataIntegrated2Hs <- AddModuleScore(object = DataIntegrated2Hs, features = genelist5, name = "genelist5")

FeaturePlot(object = DataIntegrated2Hs, features = "genelist5", order = T) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral"))) & NoAxes()

```

```{r}

genelist6 <- list(c("BMP5", "BMP7", "WNT5A"))

DataIntegrated2Hs <- AddModuleScore(object = DataIntegrated2Hs, features = genelist6, name = "genelist6")

FeaturePlot(object = DataIntegrated2Hs, features = "genelist6", order = T) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral"))) & NoAxes()

```

```{r}

DefaultAssay(DataIntegrated2Hs) <- "RNA"

FeaturePlot(DataIntegrated2Hs, c("TNC", "CD55", "WNT4", "LAMA5", "LGR5", "ADAMTS18",  "WIF1", "BMP3", "ACTA2"), order =T) & NoAxes()

```

```{r}
DataIntegrated2HsSub <- subset(DataIntegrated2Hs, idents = c("LP_SMC", "MM_SMC/MP_SMC"))

DefaultAssay(DataIntegrated2HsSub) <- "integrated"

DataIntegrated2HsSub <- RunPCA(DataIntegrated2HsSub, verbose = FALSE)
ElbowPlot(DataIntegrated2HsSub)
DataIntegrated2HsSub <- RunUMAP(DataIntegrated2HsSub, reduction = "pca", dims = 1:10)

DataIntegrated2HsSub <- FindNeighbors(DataIntegrated2HsSub, reduction = "pca", dims = 1:10)
DataIntegrated2HsSub <- FindClusters(DataIntegrated2HsSub, resolution = 0.2)

DimPlot(DataIntegrated2HsSub, reduction = "umap", label = T)

```

```{r}

ClusterIDs <- c( "myocytes", "MM SMC", "MP SMC", "ICC")
names(ClusterIDs) <- levels(DataIntegrated2HsSub)
DataIntegrated2HsSub <- RenameIdents(DataIntegrated2HsSub, ClusterIDs)

DimPlot(DataIntegrated2HsSub, reduction = "umap", label = T)

DimPlot(DataIntegrated2HsSub, reduction = "umap", label = F, cols = c("myocytes" = "#D54B76","MM SMC" = "#F6AEE5", "MP SMC" = "#C59ED4", "ICC" = "#883AA6"), pt.size = 1.4) & NoAxes()

```

```{r}

genes <- c("ACTA2", "MYH11",  "ACTG2", "DES", "HHIP", "KIT")

DefaultAssay(DataIntegrated2HsSub) <- "RNA"

StackedVlnPlot(DataIntegrated2HsSub, genes,  cols = c("myocytes" = "#D54B76","MM SMC" = "#F6AEE5", "MP SMC" = "#C59ED4", "ICC" = "#883AA6"))

```

```{r}

Markers <- FindMarkers(DataIntegrated2HsSub, ident.1 = c("myocytes"), only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, min.diff.pct = 0.5, assay = "RNA")

Markers <- FindMarkers(DataIntegrated2Sub, ident.1 = c("MM SMC"), only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, min.diff.pct = 0.25, assay = "RNA")

Markers <- FindMarkers(DataIntegrated2Sub, ident.1 = c("MP SMC"), only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, min.diff.pct = 0.4, assay = "RNA")

Markers <- FindMarkers(DataIntegrated2Sub, ident.1 = c("ICC"), only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, min.diff.pct = 0.5, assay = "RNA")

```

```{r}

DataIntegrated2Sub@active.ident <- factor(DataIntegrated2Sub@active.ident,
                                       levels = c( "ICC",  "MP SMC","MM SMC","myocytes"))

genes <- c( "HHIP","NPNT", "SOSTDC1", "DIO2",
           "GREM1", "GREM2", "RSPO2", "CHRDL1", "C2orf40",
           "SMPX" , "TACR2", "PNCK", "POPDC2")

DotPlot(DataIntegrated2Sub, assay = "RNA", dot.min = 0.05,  genes, scale.by = "size")+
    theme(axis.text=element_text(angle=90))

```

```{r}

genelist7 <- list(c("SMPX", "TACR2", "PNCK", "POPDC2"))
DataIntegrated2Hs <- AddModuleScore(object = DataIntegrated2Hs, features = genelist7, name = "genelist7")

FeaturePlot(object = DataIntegrated2Hs, features = "genelist7", order = T) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral"))) & NoAxes()

```

```{r}

genelist8 <- list(c("HHIP","NPNT", "SOSTDC1", "DIO2"))
DataIntegrated2Hs <- AddModuleScore(object = DataIntegrated2Hs, features = genelist8, name = "genelist8")

FeaturePlot(object = DataIntegrated2Hs, features = "genelist8", order = T) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral"))) & NoAxes()

```

```{r}

genelist9 <- list(c("GREM1", "GREM2", "RSPO2", "CHRDL1", "C2orf40"))
DataIntegrated2Hs <- AddModuleScore(object = DataIntegrated2Hs, features = ghenelist9, name = "ghenelist9")

FeaturePlot(object = DataIntegrated2Hs, features = "ghenelist9", order = T) & scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "Spectral"))) & NoAxes()

```

```{r}

Markers <- FindMarkers(DataIntegrated2Hs, ident.1 = c("MIF"), only.pos = TRUE, min.pct = 0.5, logfc.threshold = 0.5, min.diff.pct = 0.5, assay = "RNA")

genes <- Markers %>%
  top_n(n = 30, wt = avg_log2FC)

genes <- rownames(Markers)
genes <- sort(genes)

DotPlot(DataIntegrated2Hs, assay = "RNA", dot.min = 0.05, genes, scale.by = "size", col.min = 0)+
    theme(axis.text=element_text(angle=90))

```

```{r}

genes <- c( "KCNN3", "P2RY1", "RAMP1", "PID1",  "THBS2", "JAM2",  "FXYD6" )

DotPlot(DataIntegrated2Hs, assay = "RNA", dot.min = 0.05,  genes, scale.by = "size", col.min = 0)+
    #scale_size(range = c(0.01, 100))+
    theme(axis.text=element_text(angle=90))

```


```{r}

MIFsHs <- FindMarkers(DataIntegrated2Hs, "MIF", assay = "RNA")
MIFsMFHs <- FindMarkers(DataIntegrated2Hs, "MIF", assay = "RNA", min.pct = 0.25)

MIFsHs$gene <- rownames(MIFsHs)
MIFsHs <- subset(MIFsHs, select = c(avg_log2FC, gene))

MIFsMFHs$gene <- rownames(MIFsMFHs)
MIFsMFHs <- subset(MIFsMFHs, select = c(avg_log2FC, gene))

WriteXLS(MIFsHs, "/dir/Hs_Normal/MIF_markersHs.xlsx")
WriteXLS(MIFsMFHs, "/dir/Hs_Normal/MIF_markersHsMF.xlsx")

```

